#' SCCP_isotope_df
#'
#' A dataframe generated by the default settings in gen_CP_isotope_df. It
#' contains data for the three (3) most abundant isotopes of Short-chain
#' chlorinated paraffins (SCCPs) with carbon numbers ranging from 10 to 13 and
#' chlorine numbers ranging from 5 to 10. It is used by default for most SCCP
#' processing.
#'
#' @format A dataframe with 72 rows and 13 variables:
#'   \describe{\item{chem_formula}{SCCP chemical formula, a character string}
#'   \item{compound}{abbreviated SCCP chemical formula, a character string}
#'   \item{perc_Cl}{weight percent Cl (%Cl), in percent notation, a numeric}
#'   \item{neutral}{accurate mass of neutral isotopic formula, in decimal
#'   unified atomic mass units (u), a numeric} \item{rel_isotop_abund}{relative
#'   isotopic abundance, in decimal rather than percent notation, a numeric}
#'   \item{frac_isotop_abund}{fractional relative isotopic abundance, in decimal
#'   rather than percent notation, computed as a fraction of all relative
#'   isotopic abundances, a numeric} \item{'M-Cl'}{accurate mass of negative
#'   [M-Cl] ion, in decimal unified atomic mass units (u), a numeric} ... }
#' @source gen_enhanced_isotope_list package
#' @examples
#' data(SCCP_isotope_df)
"SCCP_isotope_df"
